# Generated by Django 4.2.1 on 2024-08-01 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cart", "0016_remove_wishlist_buy_now"),
        ("warranty", "0002_warranty_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="warranty",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cart.order",
            ),
        ),
    ]
